### ISSUE TITLE
Why do we have gen options in est function?

### ISSUE THREAD

**Issue by rkillick** [EuanMcGonigle/TrendLSW#1]
Why do we have the gen.filter.number and gen.family argments in the TLSW.est function?  The user isn't going to know this and will likely just put the same as the analysing wavelet or leave the defaults.  Seems strange to have them as an early option in the argument list.

**Comment by EuanMcGonigle** [comment]
I've updated this now, so that gen.family and gen.filter.number are the last arguments of the function, and the default is the same as the analysing wavelet. In the documentation I've updated it to mention it's recommended leaving as default.
