### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [EuanMcGonigle/TrendLSW#4]
I suggest adding the topics `wavelets`, `wavelet-analysis`, `time-series-analysis`, `time-series`, `trend`, `spectrum`, `spectral-analysis`, `r-package` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by EuanMcGonigle** [comment]
Thanks, I have added topics now.
